In [1]:
import pandas as pd
import numpy as np
from datetime import datetime

data = {
    'EmployeeID': [101, 102, 103, 104, 105],
    'Name': ['Alice', 'Bob', 'Charlie', 'Diana', 'Ethan'],
    'Department': ['Sales', 'Engineering', 'HR', 'Engineering', 'Sales'],
    'Salary': [55000, 80000, 50000, 90000, 60000],
    'JoinDate': ['2020-01-15', '2019-07-23', '2021-03-01', '2018-12-12', '2020-06-30'],
    'PerformanceScore': [4.5, 3.8, 4.2, 4.0, 3.9]
}
df = pd.DataFrame(data)
df['JoinDate'] = pd.to_datetime(df['JoinDate'])

In [2]:
df

   EmployeeID     Name   Department  Salary   JoinDate  PerformanceScore
0         101    Alice        Sales   55000 2020-01-15               4.5
1         102      Bob  Engineering   80000 2019-07-23               3.8
2         103  Charlie           HR   50000 2021-03-01               4.2
3         104    Diana  Engineering   90000 2018-12-12               4.0
4         105    Ethan        Sales   60000 2020-06-30               3.9

In [3]:
# apply (map)

In [4]:
def func(x):
    if x > 4:
        return "+"
    return "-"

In [5]:
df['PerformanceScore'].map(func)

0    +
1    -
2    +
3    -
4    -
Name: PerformanceScore, dtype: object

In [6]:
df['PerformanceScore'].apply(func)

0    +
1    -
2    +
3    -
4    -
Name: PerformanceScore, dtype: object

In [7]:
### Базовые операции в apply

In [8]:
df

   EmployeeID     Name   Department  Salary   JoinDate  PerformanceScore
0         101    Alice        Sales   55000 2020-01-15               4.5
1         102      Bob  Engineering   80000 2019-07-23               3.8
2         103  Charlie           HR   50000 2021-03-01               4.2
3         104    Diana  Engineering   90000 2018-12-12               4.0
4         105    Ethan        Sales   60000 2020-06-30               3.9

In [9]:
def upper_name(name):
    return name.upper()

In [10]:
df['Name_Upper_1'] = df['Name'].apply(upper_name)

In [11]:
df

,EmployeeID,Name,Department,Salary,JoinDate,PerformanceScore,Name_Upper_1
0,101,Alice,Sales,55000,2020-01-15,4.5,ALICE
1,102,Bob,Engineering,80000,2019-07-23,3.8,BOB
2,103,Charlie,HR,50000,2021-03-01,4.2,CHARLIE
3,104,Diana,Engineering,90000,2018-12-12,4.0,DIANA
4,105,Ethan,Sales,60000,2020-06-30,3.9,ETHAN

In [12]:
df['Name_Upper_2'] = df['Name'].apply(lambda name: name.upper())

In [13]:
df

,EmployeeID,Name,Department,Salary,JoinDate,PerformanceScore,Name_Upper_1,Name_Upper_2
0,101,Alice,Sales,55000,2020-01-15,4.5,ALICE,ALICE
1,102,Bob,Engineering,80000,2019-07-23,3.8,BOB,BOB
2,103,Charlie,HR,50000,2021-03-01,4.2,CHARLIE,CHARLIE
3,104,Diana,Engineering,90000,2018-12-12,4.0,DIANA,DIANA
4,105,Ethan,Sales,60000,2020-06-30,3.9,ETHAN,ETHAN

In [14]:
def first_letter(name):
    return name[0]

In [15]:
df['Name_Initial'] = df['Name'].apply(first_letter)

In [16]:
df

,EmployeeID,Name,Department,Salary,JoinDate,PerformanceScore,Name_Upper_1,Name_Upper_2,Name_Initial
0,101,Alice,Sales,55000,2020-01-15,4.5,ALICE,ALICE,A
1,102,Bob,Engineering,80000,2019-07-23,3.8,BOB,BOB,B
2,103,Charlie,HR,50000,2021-03-01,4.2,CHARLIE,CHARLIE,C
3,104,Diana,Engineering,90000,2018-12-12,4.0,DIANA,DIANA,D
4,105,Ethan,Sales,60000,2020-06-30,3.9,ETHAN,ETHAN,E

In [17]:
df['Name_Initial_2'] = df['Name'].apply(lambda name: name[0])

In [18]:
df

,EmployeeID,Name,Department,Salary,JoinDate,PerformanceScore,Name_Upper_1,Name_Upper_2,Name_Initial,Name_Initial_2
0,101,Alice,Sales,55000,2020-01-15,4.5,ALICE,ALICE,A,A
1,102,Bob,Engineering,80000,2019-07-23,3.8,BOB,BOB,B,B
2,103,Charlie,HR,50000,2021-03-01,4.2,CHARLIE,CHARLIE,C,C
3,104,Diana,Engineering,90000,2018-12-12,4.0,DIANA,DIANA,D,D
4,105,Ethan,Sales,60000,2020-06-30,3.9,ETHAN,ETHAN,E,E

In [19]:
## Извлечение года

In [20]:
def get_year(date):
    return date.year

In [21]:
df['JoinYear_1'] = df['JoinDate'].apply(get_year)

In [22]:
df

,EmployeeID,Name,Department,Salary,JoinDate,PerformanceScore,Name_Upper_1,Name_Upper_2,Name_Initial,Name_Initial_2,JoinYear_1
0,101,Alice,Sales,55000,2020-01-15,4.5,ALICE,ALICE,A,A,2020
1,102,Bob,Engineering,80000,2019-07-23,3.8,BOB,BOB,B,B,2019
2,103,Charlie,HR,50000,2021-03-01,4.2,CHARLIE,CHARLIE,C,C,2021
3,104,Diana,Engineering,90000,2018-12-12,4.0,DIANA,DIANA,D,D,2018
4,105,Ethan,Sales,60000,2020-06-30,3.9,ETHAN,ETHAN,E,E,2020

In [23]:
df['JoinYear_2'] = df['JoinDate'].apply(lambda date: date.year)

In [24]:
df

,EmployeeID,Name,Department,Salary,JoinDate,PerformanceScore,Name_Upper_1,Name_Upper_2,Name_Initial,Name_Initial_2,JoinYear_1,JoinYear_2
0,101,Alice,Sales,55000,2020-01-15,4.5,ALICE,ALICE,A,A,2020,2020
1,102,Bob,Engineering,80000,2019-07-23,3.8,BOB,BOB,B,B,2019,2019
2,103,Charlie,HR,50000,2021-03-01,4.2,CHARLIE,CHARLIE,C,C,2021,2021
3,104,Diana,Engineering,90000,2018-12-12,4.0,DIANA,DIANA,D,D,2018,2018
4,105,Ethan,Sales,60000,2020-06-30,3.9,ETHAN,ETHAN,E,E,2020,2020

In [25]:
df['Dept_Len'] = df['Department'].apply(lambda dep: len(dep))

In [26]:
df

,EmployeeID,Name,Department,Salary,JoinDate,PerformanceScore,Name_Upper_1,Name_Upper_2,Name_Initial,Name_Initial_2,JoinYear_1,JoinYear_2,Dept_Len
0,101,Alice,Sales,55000,2020-01-15,4.5,ALICE,ALICE,A,A,2020,2020,5
1,102,Bob,Engineering,80000,2019-07-23,3.8,BOB,BOB,B,B,2019,2019,11
2,103,Charlie,HR,50000,2021-03-01,4.2,CHARLIE,CHARLIE,C,C,2021,2021,2
3,104,Diana,Engineering,90000,2018-12-12,4.0,DIANA,DIANA,D,D,2018,2018,11
4,105,Ethan,Sales,60000,2020-06-30,3.9,ETHAN,ETHAN,E,E,2020,2020,5

In [27]:
len("Engineering")

11

In [28]:
### Пощупаем apply

In [29]:
def print_val(x):
    print(x, type(x))

In [30]:
df['Name'].apply(print_val)

Alice <class 'str'>
Bob <class 'str'>
Charlie <class 'str'>
Diana <class 'str'>
Ethan <class 'str'>

0    None
1    None
2    None
3    None
4    None
Name: Name, dtype: object

In [31]:
## Еще чуть-чуть про лямбду

In [32]:
df

,EmployeeID,Name,Department,Salary,JoinDate,PerformanceScore,Name_Upper_1,Name_Upper_2,Name_Initial,Name_Initial_2,JoinYear_1,JoinYear_2,Dept_Len
0,101,Alice,Sales,55000,2020-01-15,4.5,ALICE,ALICE,A,A,2020,2020,5
1,102,Bob,Engineering,80000,2019-07-23,3.8,BOB,BOB,B,B,2019,2019,11
2,103,Charlie,HR,50000,2021-03-01,4.2,CHARLIE,CHARLIE,C,C,2021,2021,2
3,104,Diana,Engineering,90000,2018-12-12,4.0,DIANA,DIANA,D,D,2018,2018,11
4,105,Ethan,Sales,60000,2020-06-30,3.9,ETHAN,ETHAN,E,E,2020,2020,5

In [33]:
def get_score_desc(score):
    if score > 4:
        return 'High'
    return 'Standart'

In [34]:
df['ScoreDesc_1'] = df['PerformanceScore'].apply(get_score_desc)

In [35]:
df[['Name', 'PerformanceScore', 'ScoreDesc_1']]

      Name  PerformanceScore ScoreDesc_1
0    Alice               4.5        High
1      Bob               3.8    Standart
2  Charlie               4.2        High
3    Diana               4.0    Standart
4    Ethan               3.9    Standart

In [36]:
df['ScoreDesc_2'] = df['PerformanceScore'].apply(lambda score: "High" if score > 4 else "Standart")

In [37]:
df[['Name', 'PerformanceScore', 'ScoreDesc_1', 'ScoreDesc_2']]

      Name  PerformanceScore ScoreDesc_1 ScoreDesc_2
0    Alice               4.5        High        High
1      Bob               3.8    Standart    Standart
2  Charlie               4.2        High        High
3    Diana               4.0    Standart    Standart
4    Ethan               3.9    Standart    Standart

In [38]:
df.columns

Index(['EmployeeID', 'Name', 'Department', 'Salary', 'JoinDate',
       'PerformanceScore', 'Name_Upper_1', 'Name_Upper_2', 'Name_Initial',
       'Name_Initial_2', 'JoinYear_1', 'JoinYear_2', 'Dept_Len', 'ScoreDesc_1',
       'ScoreDesc_2'],
      dtype='object')

In [39]:
df = df.drop(['Name_Upper_1', 'Name_Upper_2', 'Name_Initial',
       'Name_Initial_2', 'JoinYear_1', 'JoinYear_2', 'Dept_Len', 'ScoreDesc_1',
       'ScoreDesc_2'], axis=1)

In [40]:
## apply с несколькими колонками

In [41]:
df

   EmployeeID     Name   Department  Salary   JoinDate  PerformanceScore
0         101    Alice        Sales   55000 2020-01-15               4.5
1         102      Bob  Engineering   80000 2019-07-23               3.8
2         103  Charlie           HR   50000 2021-03-01               4.2
3         104    Diana  Engineering   90000 2018-12-12               4.0
4         105    Ethan        Sales   60000 2020-06-30               3.9

In [42]:
def calc_new_salary(x):
    print(x)
    print('---')

In [43]:
df[['Department', 'Salary']].apply(calc_new_salary)

0          Sales
1    Engineering
2             HR
3    Engineering
4          Sales
Name: Department, dtype: object
---
0    55000
1    80000
2    50000
3    90000
4    60000
Name: Salary, dtype: int64
---

Department    None
Salary        None
dtype: object

In [44]:
df[['Department', 'Salary']].apply(calc_new_salary, axis=0)

0          Sales
1    Engineering
2             HR
3    Engineering
4          Sales
Name: Department, dtype: object
---
0    55000
1    80000
2    50000
3    90000
4    60000
Name: Salary, dtype: int64
---

Department    None
Salary        None
dtype: object

In [45]:
df[['Department', 'Salary']].apply(calc_new_salary, axis=1)

Department    Sales
Salary        55000
Name: 0, dtype: object
---
Department    Engineering
Salary              80000
Name: 1, dtype: object
---
Department       HR
Salary        50000
Name: 2, dtype: object
---
Department    Engineering
Salary              90000
Name: 3, dtype: object
---
Department    Sales
Salary        60000
Name: 4, dtype: object
---

0    None
1    None
2    None
3    None
4    None
dtype: object

In [46]:
def calc_new_salary_2(x):
    if x['Department'] == 'Engineering':
        return x['Salary'] * 2
    return x['Salary']

In [47]:
df['NewSalary'] = df[['Department', 'Salary']].apply(calc_new_salary_2, axis=1)

In [48]:
df

,EmployeeID,Name,Department,Salary,JoinDate,PerformanceScore,NewSalary
0,101,Alice,Sales,55000,2020-01-15,4.5,55000
1,102,Bob,Engineering,80000,2019-07-23,3.8,160000
2,103,Charlie,HR,50000,2021-03-01,4.2,50000
3,104,Diana,Engineering,90000,2018-12-12,4.0,180000
4,105,Ethan,Sales,60000,2020-06-30,3.9,60000

In [49]:
df[['Department', 'Salary']].apply(calc_new_salary_2)

KeyError: 'Department'

In [ ]:
def calc_mean_salary(x):
    return x.mean()

In [ ]:
df[['Salary', 'NewSalary']].apply(calc_mean_salary)

In [ ]:
df['Salary'].mean()

In [ ]:
df['NewSalary'].mean()

In [ ]:
## А как тоже самое, но с лямбдой?

In [50]:
df

,EmployeeID,Name,Department,Salary,JoinDate,PerformanceScore,NewSalary
0,101,Alice,Sales,55000,2020-01-15,4.5,55000
1,102,Bob,Engineering,80000,2019-07-23,3.8,160000
2,103,Charlie,HR,50000,2021-03-01,4.2,50000
3,104,Diana,Engineering,90000,2018-12-12,4.0,180000
4,105,Ethan,Sales,60000,2020-06-30,3.9,60000

In [51]:
df['NewSalarySales'] = df[['Department', 'Salary']].apply(lambda row: row['Salary'] * 3 if row['Department'] == 'Sales' else row['Salary'], axis=1)

In [52]:
df

,EmployeeID,Name,Department,Salary,JoinDate,PerformanceScore,NewSalary,NewSalarySales
0,101,Alice,Sales,55000,2020-01-15,4.5,55000,165000
1,102,Bob,Engineering,80000,2019-07-23,3.8,160000,80000
2,103,Charlie,HR,50000,2021-03-01,4.2,50000,50000
3,104,Diana,Engineering,90000,2018-12-12,4.0,180000,90000
4,105,Ethan,Sales,60000,2020-06-30,3.9,60000,180000

In [53]:
## Применяем apply ко всему датасету сразу!

In [54]:
def describe_employee(row):
    current_year = datetime.now().year
    tenure = current_year - row['JoinDate'].year
    return f"{row['Name']} из департамента {row['Department']}, зарплата {row['Salary']}, оценка {row['PerformanceScore']}, стаж {tenure}"

In [55]:
df['Info'] = df.apply(describe_employee, axis=1)

In [56]:
df['Info'].values

array(['Alice из департамента Sales, зарплата 55000, оценка 4.5, стаж 5',
       'Bob из департамента Engineering, зарплата 80000, оценка 3.8, стаж 6',
       'Charlie из департамента HR, зарплата 50000, оценка 4.2, стаж 4',
       'Diana из департамента Engineering, зарплата 90000, оценка 4.0, стаж 7',
       'Ethan из департамента Sales, зарплата 60000, оценка 3.9, стаж 5'],
      dtype=object)

In [57]:
df

,EmployeeID,Name,Department,Salary,JoinDate,PerformanceScore,NewSalary,NewSalarySales,Info
0,101,Alice,Sales,55000,2020-01-15,4.5,55000,165000,"Alice из департамента Sales, зарплата 55000, о..."
1,102,Bob,Engineering,80000,2019-07-23,3.8,160000,80000,"Bob из департамента Engineering, зарплата 8000..."
2,103,Charlie,HR,50000,2021-03-01,4.2,50000,50000,"Charlie из департамента HR, зарплата 50000, оц..."
3,104,Diana,Engineering,90000,2018-12-12,4.0,180000,90000,"Diana из департамента Engineering, зарплата 90..."
4,105,Ethan,Sales,60000,2020-06-30,3.9,60000,180000,"Ethan из департамента Sales, зарплата 60000, о..."

In [58]:
# Премия 5% от Salary
## PerformanceScore  < 4 тогда получает 50%

In [59]:
def calc_bonus(row):
    base = 0.05 * row['Salary']
    #bonus = base if row['PerformanceScore'] >= 4 else base * 0.5
    if row['PerformanceScore'] >= 4:
        return base
    else:
        return base * 0.5

In [60]:
df['CalculatedBonus'] = df.apply(calc_bonus, axis=1)

In [61]:
df

,EmployeeID,Name,Department,Salary,JoinDate,PerformanceScore,NewSalary,NewSalarySales,Info,CalculatedBonus
0,101,Alice,Sales,55000,2020-01-15,4.5,55000,165000,"Alice из департамента Sales, зарплата 55000, о...",2750.0
1,102,Bob,Engineering,80000,2019-07-23,3.8,160000,80000,"Bob из департамента Engineering, зарплата 8000...",2000.0
2,103,Charlie,HR,50000,2021-03-01,4.2,50000,50000,"Charlie из департамента HR, зарплата 50000, оц...",2500.0
3,104,Diana,Engineering,90000,2018-12-12,4.0,180000,90000,"Diana из департамента Engineering, зарплата 90...",4500.0
4,105,Ethan,Sales,60000,2020-06-30,3.9,60000,180000,"Ethan из департамента Sales, зарплата 60000, о...",1500.0

In [62]:
60000 * 0.05 * 0.5

1500.0

In [63]:
# Категоризация сотрудников:
## Топовый сотрудник: зарплата > 75000 и оценка >= 4
## Требует улучшений: зарплата <= 75000 и оценка ниже 4
## Средний сотрудник

In [64]:
def categorize_employee(row):
    if row['Salary'] > 75_000 and row['PerformanceScore'] >= 4:
        return 'Top'
    elif row['Salary'] <= 75_000 and row['PerformanceScore'] < 4:
        return 'Needs Improvement'
    else:
        return 'Average'

In [65]:
df['Category'] = df.apply(categorize_employee, axis=1)

In [66]:
df

,EmployeeID,Name,Department,Salary,JoinDate,PerformanceScore,NewSalary,NewSalarySales,Info,CalculatedBonus,Category
0,101,Alice,Sales,55000,2020-01-15,4.5,55000,165000,"Alice из департамента Sales, зарплата 55000, о...",2750.0,Average
1,102,Bob,Engineering,80000,2019-07-23,3.8,160000,80000,"Bob из департамента Engineering, зарплата 8000...",2000.0,Average
2,103,Charlie,HR,50000,2021-03-01,4.2,50000,50000,"Charlie из департамента HR, зарплата 50000, оц...",2500.0,Average
3,104,Diana,Engineering,90000,2018-12-12,4.0,180000,90000,"Diana из департамента Engineering, зарплата 90...",4500.0,Top
4,105,Ethan,Sales,60000,2020-06-30,3.9,60000,180000,"Ethan из департамента Sales, зарплата 60000, о...",1500.0,Needs Improvement

In [67]:
## apply для редактирования датафрейма

In [68]:
def fix_names(x):
    x['Name'] = x['Name'].upper()
    x['Department'] = x['Department'].lower()
    return x

In [69]:
df = df.apply(fix_names, axis=1)

In [70]:
df

,EmployeeID,Name,Department,Salary,JoinDate,PerformanceScore,NewSalary,NewSalarySales,Info,CalculatedBonus,Category
0,101,ALICE,sales,55000,2020-01-15,4.5,55000,165000,"Alice из департамента Sales, зарплата 55000, о...",2750.0,Average
1,102,BOB,engineering,80000,2019-07-23,3.8,160000,80000,"Bob из департамента Engineering, зарплата 8000...",2000.0,Average
2,103,CHARLIE,hr,50000,2021-03-01,4.2,50000,50000,"Charlie из департамента HR, зарплата 50000, оц...",2500.0,Average
3,104,DIANA,engineering,90000,2018-12-12,4.0,180000,90000,"Diana из департамента Engineering, зарплата 90...",4500.0,Top
4,105,ETHAN,sales,60000,2020-06-30,3.9,60000,180000,"Ethan из департамента Sales, зарплата 60000, о...",1500.0,Needs Improvement

In [71]:
## Работа с вложенными структурами

In [72]:
projects = {
    101: ['Project A', 'Project B'],
    102: ['Project C'],
    103: [],
    104: ['Project D', 'Project E', 'Project F'],
    105: ['Project G']
}
df['Projects'] = df['EmployeeID'].map(projects)
print(df[['EmployeeID', 'Projects']])

   EmployeeID                           Projects
0         101             [Project A, Project B]
1         102                        [Project C]
2         103                                 []
3         104  [Project D, Project E, Project F]
4         105                        [Project G]

In [73]:
df

,EmployeeID,Name,Department,Salary,JoinDate,PerformanceScore,NewSalary,NewSalarySales,Info,CalculatedBonus,Category,Projects
0,101,ALICE,sales,55000,2020-01-15,4.5,55000,165000,"Alice из департамента Sales, зарплата 55000, о...",2750.0,Average,"[Project A, Project B]"
1,102,BOB,engineering,80000,2019-07-23,3.8,160000,80000,"Bob из департамента Engineering, зарплата 8000...",2000.0,Average,[Project C]
2,103,CHARLIE,hr,50000,2021-03-01,4.2,50000,50000,"Charlie из департамента HR, зарплата 50000, оц...",2500.0,Average,[]
3,104,DIANA,engineering,90000,2018-12-12,4.0,180000,90000,"Diana из департамента Engineering, зарплата 90...",4500.0,Top,"[Project D, Project E, Project F]"
4,105,ETHAN,sales,60000,2020-06-30,3.9,60000,180000,"Ethan из департамента Sales, зарплата 60000, о...",1500.0,Needs Improvement,[Project G]

In [74]:
# Извлечение первого проекта для каждого сотрудника

In [75]:
df['FirstProject'] = df['Projects'].apply(lambda projs: projs[0] if len(projs) > 0 else None)

In [76]:
df

,EmployeeID,Name,Department,Salary,JoinDate,PerformanceScore,NewSalary,NewSalarySales,Info,CalculatedBonus,Category,Projects,FirstProject
0,101,ALICE,sales,55000,2020-01-15,4.5,55000,165000,"Alice из департамента Sales, зарплата 55000, о...",2750.0,Average,"[Project A, Project B]",Project A
1,102,BOB,engineering,80000,2019-07-23,3.8,160000,80000,"Bob из департамента Engineering, зарплата 8000...",2000.0,Average,[Project C],Project C
2,103,CHARLIE,hr,50000,2021-03-01,4.2,50000,50000,"Charlie из департамента HR, зарплата 50000, оц...",2500.0,Average,[],None
3,104,DIANA,engineering,90000,2018-12-12,4.0,180000,90000,"Diana из департамента Engineering, зарплата 90...",4500.0,Top,"[Project D, Project E, Project F]",Project D
4,105,ETHAN,sales,60000,2020-06-30,3.9,60000,180000,"Ethan из департамента Sales, зарплата 60000, о...",1500.0,Needs Improvement,[Project G],Project G

In [77]:
# Посчитать количество проектов для каждого сотрудника

In [78]:
df['ProjectCount'] = df['Projects'].apply(lambda projs: len(projs))

In [79]:
df

,EmployeeID,Name,Department,Salary,JoinDate,PerformanceScore,NewSalary,NewSalarySales,Info,CalculatedBonus,Category,Projects,FirstProject,ProjectCount
0,101,ALICE,sales,55000,2020-01-15,4.5,55000,165000,"Alice из департамента Sales, зарплата 55000, о...",2750.0,Average,"[Project A, Project B]",Project A,2
1,102,BOB,engineering,80000,2019-07-23,3.8,160000,80000,"Bob из департамента Engineering, зарплата 8000...",2000.0,Average,[Project C],Project C,1
2,103,CHARLIE,hr,50000,2021-03-01,4.2,50000,50000,"Charlie из департамента HR, зарплата 50000, оц...",2500.0,Average,[],None,0
3,104,DIANA,engineering,90000,2018-12-12,4.0,180000,90000,"Diana из департамента Engineering, зарплата 90...",4500.0,Top,"[Project D, Project E, Project F]",Project D,3
4,105,ETHAN,sales,60000,2020-06-30,3.9,60000,180000,"Ethan из департамента Sales, зарплата 60000, о...",1500.0,Needs Improvement,[Project G],Project G,1

In [80]:
# Формирование строки со списком проектов

In [81]:
df['Projects_str'] = df['Projects'].apply(lambda projs: ', '.join(projs) if projs else 'No Projects')

In [82]:
df

,EmployeeID,Name,Department,Salary,JoinDate,PerformanceScore,NewSalary,NewSalarySales,Info,CalculatedBonus,Category,Projects,FirstProject,ProjectCount,Projects_str
0,101,ALICE,sales,55000,2020-01-15,4.5,55000,165000,"Alice из департамента Sales, зарплата 55000, о...",2750.0,Average,"[Project A, Project B]",Project A,2,"Project A, Project B"
1,102,BOB,engineering,80000,2019-07-23,3.8,160000,80000,"Bob из департамента Engineering, зарплата 8000...",2000.0,Average,[Project C],Project C,1,Project C
2,103,CHARLIE,hr,50000,2021-03-01,4.2,50000,50000,"Charlie из департамента HR, зарплата 50000, оц...",2500.0,Average,[],None,0,No Projects
3,104,DIANA,engineering,90000,2018-12-12,4.0,180000,90000,"Diana из департамента Engineering, зарплата 90...",4500.0,Top,"[Project D, Project E, Project F]",Project D,3,"Project D, Project E, Project F"
4,105,ETHAN,sales,60000,2020-06-30,3.9,60000,180000,"Ethan из департамента Sales, зарплата 60000, о...",1500.0,Needs Improvement,[Project G],Project G,1,Project G

In [83]:
# Фильтрация через apply

In [84]:
df[df['Projects'].apply(lambda projs: len(projs) > 0)]

,EmployeeID,Name,Department,Salary,JoinDate,PerformanceScore,NewSalary,NewSalarySales,Info,CalculatedBonus,Category,Projects,FirstProject,ProjectCount,Projects_str
0,101,ALICE,sales,55000,2020-01-15,4.5,55000,165000,"Alice из департамента Sales, зарплата 55000, о...",2750.0,Average,"[Project A, Project B]",Project A,2,"Project A, Project B"
1,102,BOB,engineering,80000,2019-07-23,3.8,160000,80000,"Bob из департамента Engineering, зарплата 8000...",2000.0,Average,[Project C],Project C,1,Project C
3,104,DIANA,engineering,90000,2018-12-12,4.0,180000,90000,"Diana из департамента Engineering, зарплата 90...",4500.0,Top,"[Project D, Project E, Project F]",Project D,3,"Project D, Project E, Project F"
4,105,ETHAN,sales,60000,2020-06-30,3.9,60000,180000,"Ethan из департамента Sales, зарплата 60000, о...",1500.0,Needs Improvement,[Project G],Project G,1,Project G

In [85]:
df['Projects'].apply(lambda projs: len(projs) > 0)

0     True
1     True
2    False
3     True
4     True
Name: Projects, dtype: bool

In [86]:
# Apply и создание нескольких колонок сразу

In [87]:
def extract_year(row):
    return row['JoinDate'].year

def extract_month(row):
    return row['JoinDate'].month

def extract_day(row):
    return row['JoinDate'].day

In [88]:
df.apply(extract_year, axis=1)

0    2020
1    2019
2    2021
3    2018
4    2020
dtype: int64

In [89]:
df.apply(extract_month, axis=1)

0     1
1     7
2     3
3    12
4     6
dtype: int64

In [90]:
df.apply(extract_day, axis=1)

0    15
1    23
2     1
3    12
4    30
dtype: int64

In [91]:
def extract_date_info(row):
    return pd.Series({
        'Year' : row['JoinDate'].year,
        'Month' : row['JoinDate'].month,
        'Day' : row['JoinDate'].day,
    })

In [92]:
df_dates = df.apply(extract_date_info, axis=1)

In [93]:
df_dates

   Year  Month  Day
0  2020      1   15
1  2019      7   23
2  2021      3    1
3  2018     12   12
4  2020      6   30

In [94]:
pd.concat([df, df_dates], axis=1)

,EmployeeID,Name,Department,Salary,JoinDate,PerformanceScore,NewSalary,NewSalarySales,Info,CalculatedBonus,Category,Projects,FirstProject,ProjectCount,Projects_str,Year,Month,Day
0,101,ALICE,sales,55000,2020-01-15,4.5,55000,165000,"Alice из департамента Sales, зарплата 55000, о...",2750.0,Average,"[Project A, Project B]",Project A,2,"Project A, Project B",2020,1,15
1,102,BOB,engineering,80000,2019-07-23,3.8,160000,80000,"Bob из департамента Engineering, зарплата 8000...",2000.0,Average,[Project C],Project C,1,Project C,2019,7,23
2,103,CHARLIE,hr,50000,2021-03-01,4.2,50000,50000,"Charlie из департамента HR, зарплата 50000, оц...",2500.0,Average,[],None,0,No Projects,2021,3,1
3,104,DIANA,engineering,90000,2018-12-12,4.0,180000,90000,"Diana из департамента Engineering, зарплата 90...",4500.0,Top,"[Project D, Project E, Project F]",Project D,3,"Project D, Project E, Project F",2018,12,12
4,105,ETHAN,sales,60000,2020-06-30,3.9,60000,180000,"Ethan из департамента Sales, зарплата 60000, о...",1500.0,Needs Improvement,[Project G],Project G,1,Project G,2020,6,30

In [95]:
# Передача констант вместе с данными

In [96]:
def calc_bonus(row, bonus_rate):
    return row['Salary'] * bonus_rate

In [97]:
bonus_rate = 0.1

In [98]:
df['Bonus'] = df.apply(calc_bonus, axis=1, args=(bonus_rate,))

In [99]:
df['Bonus'].sum()

33500.0

In [100]:
bonus_rate = 0.2

In [101]:
df['Bonus_02'] = df.apply(calc_bonus, axis=1, args=(bonus_rate,))

In [102]:
df['Bonus_02'].sum()

67000.0

In [103]:
# Функция похитрее

In [104]:
# Salary > 70_000 -> salary * 0.1

In [105]:
def conditional_bonus(row, bonus_rate, threshold):
    if row['Salary'] > threshold:
        return row['Salary'] * bonus_rate
    return 0

In [106]:
df['ConditionalBonus'] = df.apply(conditional_bonus, axis=1, args=(0.1, 70_000))

In [107]:
df

,EmployeeID,Name,Department,Salary,JoinDate,PerformanceScore,NewSalary,NewSalarySales,Info,CalculatedBonus,Category,Projects,FirstProject,ProjectCount,Projects_str,Bonus,Bonus_02,ConditionalBonus
0,101,ALICE,sales,55000,2020-01-15,4.5,55000,165000,"Alice из департамента Sales, зарплата 55000, о...",2750.0,Average,"[Project A, Project B]",Project A,2,"Project A, Project B",5500.0,11000.0,0.0
1,102,BOB,engineering,80000,2019-07-23,3.8,160000,80000,"Bob из департамента Engineering, зарплата 8000...",2000.0,Average,[Project C],Project C,1,Project C,8000.0,16000.0,8000.0
2,103,CHARLIE,hr,50000,2021-03-01,4.2,50000,50000,"Charlie из департамента HR, зарплата 50000, оц...",2500.0,Average,[],None,0,No Projects,5000.0,10000.0,0.0
3,104,DIANA,engineering,90000,2018-12-12,4.0,180000,90000,"Diana из департамента Engineering, зарплата 90...",4500.0,Top,"[Project D, Project E, Project F]",Project D,3,"Project D, Project E, Project F",9000.0,18000.0,9000.0
4,105,ETHAN,sales,60000,2020-06-30,3.9,60000,180000,"Ethan из департамента Sales, зарплата 60000, о...",1500.0,Needs Improvement,[Project G],Project G,1,Project G,6000.0,12000.0,0.0

In [108]:
# Обработка ошибок в apply

In [109]:
data = {
    'EmployeeID': [101, 102, 103, 104, 105],
    'Name': ['Alice', 'Bob', 'Charlie', 'Diana', 'Ethan'],
    'Department': ['Sales', 'Engineering', 'HR', 'Engineering', 'Sales'],
    'Salary': [55000, 0, -50000, 0, -60000],
    'JoinDate': ['2020-01-15', '2019-07-23', '2021-03-01', '2018-12-12', '2020-06-30'],
    'PerformanceScore': ['4.5', '3,8', '4.2', '4', '3..9']
}
df = pd.DataFrame(data)
df['JoinDate'] = pd.to_datetime(df['JoinDate'])

In [110]:
df

   EmployeeID     Name   Department  Salary   JoinDate PerformanceScore
0         101    Alice        Sales   55000 2020-01-15              4.5
1         102      Bob  Engineering       0 2019-07-23              3,8
2         103  Charlie           HR  -50000 2021-03-01              4.2
3         104    Diana  Engineering       0 2018-12-12                4
4         105    Ethan        Sales  -60000 2020-06-30             3..9

In [111]:
def parse_performance(val):
    try:
        return float(val)
    except Exception:
        return np.nan

In [112]:
df['ParsedPerf'] = df['PerformanceScore'].apply(parse_performance)

In [113]:
df

,EmployeeID,Name,Department,Salary,JoinDate,PerformanceScore,ParsedPerf
0,101,Alice,Sales,55000,2020-01-15,4.5,4.5
1,102,Bob,Engineering,0,2019-07-23,"3,8",NaN
2,103,Charlie,HR,-50000,2021-03-01,4.2,4.2
3,104,Diana,Engineering,0,2018-12-12,4,4.0
4,105,Ethan,Sales,-60000,2020-06-30,3..9,NaN

In [114]:
def safe_bonus(row):
    try:
        if row['Salary'] < 0:
            raise ValueError("Invalid Salary")
        return 0.05 * row['Salary']
    except Exception as e:
        return np.nan

In [115]:
df['SafeBonus'] = df.apply(safe_bonus, axis=1)

In [116]:
df

,EmployeeID,Name,Department,Salary,JoinDate,PerformanceScore,ParsedPerf,SafeBonus
0,101,Alice,Sales,55000,2020-01-15,4.5,4.5,2750.0
1,102,Bob,Engineering,0,2019-07-23,"3,8",NaN,0.0
2,103,Charlie,HR,-50000,2021-03-01,4.2,4.2,NaN
3,104,Diana,Engineering,0,2018-12-12,4,4.0,0.0
4,105,Ethan,Sales,-60000,2020-06-30,3..9,NaN,NaN

In [117]:
def save_divide(x):
    try:
        return 100 / x['Salary']
    except Exception:
        return 0

In [118]:
df.apply(save_divide, axis=1)

0    0.001818
1    0.000000
2   -0.002000
3    0.000000
4   -0.001667
dtype: float64

In [119]:
## Подводим итоги

In [120]:
data = {
    'EmployeeID': [101, 102, 103, 104, 105],
    'Name': ['Alice', 'Bob', 'Charlie', 'Diana', 'Ethan'],
    'Department': ['Sales', 'Engineering', 'HR', 'Engineering', 'Sales'],
    'Salary': [55000, 80000, 50000, 90000, 60000],
    'JoinDate': ['2020-01-15', '2019-07-23', '2021-03-01', '2018-12-12', '2020-06-30'],
    'PerformanceScore': [4.5, 3.8, 4.2, 4.0, 3.9]
}
df = pd.DataFrame(data)
df['JoinDate'] = pd.to_datetime(df['JoinDate'])

In [121]:
df

   EmployeeID     Name   Department  Salary   JoinDate  PerformanceScore
0         101    Alice        Sales   55000 2020-01-15               4.5
1         102      Bob  Engineering   80000 2019-07-23               3.8
2         103  Charlie           HR   50000 2021-03-01               4.2
3         104    Diana  Engineering   90000 2018-12-12               4.0
4         105    Ethan        Sales   60000 2020-06-30               3.9

In [122]:
# Форматирование имени сотрудника с префиксом

In [123]:
df['FormalName'] = df['Name'].apply(lambda x: f"Employee: {x}")
df[['Name', 'FormalName']]

      Name         FormalName
0    Alice    Employee: Alice
1      Bob      Employee: Bob
2  Charlie  Employee: Charlie
3    Diana    Employee: Diana
4    Ethan    Employee: Ethan

In [124]:
# Вычисление "стажа" в годах на основе JoinDate

In [125]:
current_year = datetime.now().year
df['Tenure_Years'] = df['JoinDate'].apply(lambda d: current_year - d.year)
df[['JoinDate', 'Tenure_Years']]

    JoinDate  Tenure_Years
0 2020-01-15             5
1 2019-07-23             6
2 2021-03-01             4
3 2018-12-12             7
4 2020-06-30             5

In [126]:
# Извлечение года из даты приема

In [127]:
df['Year'] = df['JoinDate'].apply(lambda d: d.year)
df[['Name', 'JoinDate', 'Year']]

      Name   JoinDate  Year
0    Alice 2020-01-15  2020
1      Bob 2019-07-23  2019
2  Charlie 2021-03-01  2021
3    Diana 2018-12-12  2018
4    Ethan 2020-06-30  2020

In [128]:
# Вычисление количества дней стажа

In [129]:
df['Tenure_Days'] = df['JoinDate'].apply(lambda d: (datetime.now() - d).days)
df[['Name', 'JoinDate', 'Tenure_Days']]

      Name   JoinDate  Tenure_Days
0    Alice 2020-01-15         1879
1      Bob 2019-07-23         2055
2  Charlie 2021-03-01         1468
3    Diana 2018-12-12         2278
4    Ethan 2020-06-30         1712

In [130]:
# Проверка, пришёл ли сотрудник до 2020 года

In [131]:
df['JoinedBefore2020'] = df['JoinDate'].apply(lambda d: d.year < 2020)
df[['Name', 'JoinDate', 'JoinedBefore2020']]

      Name   JoinDate  JoinedBefore2020
0    Alice 2020-01-15             False
1      Bob 2019-07-23              True
2  Charlie 2021-03-01             False
3    Diana 2018-12-12              True
4    Ethan 2020-06-30             False

In [132]:
# Форматирование даты в строку формата "DD-MM-YYYY"

In [133]:
df['JoinDate_Str'] = df['JoinDate'].apply(lambda d: d.strftime('%d-%m-%Y'))
df[['Name', 'JoinDate', 'JoinDate_Str']]

      Name   JoinDate JoinDate_Str
0    Alice 2020-01-15   15-01-2020
1      Bob 2019-07-23   23-07-2019
2  Charlie 2021-03-01   01-03-2021
3    Diana 2018-12-12   12-12-2018
4    Ethan 2020-06-30   30-06-2020

In [141]:
# Долгая функция

In [144]:
import time

In [147]:
def upper_case(row):
    time.sleep(3)
    return row['Name']

In [149]:
df.apply(upper_case, axis=1)

0      Alice
1        Bob
2    Charlie
3      Diana
4      Ethan
dtype: object

In [150]:
from tqdm import tqdm

In [153]:
for i in tqdm(range(5)):
    j = i + i
    time.sleep(3)

100%|████████████████████████████████████████████████████████████████████████████████████| 5/5 [00:15<00:00,  3.00s/it]

In [154]:
### Поддержка tqdm в pandas

In [155]:
tqdm.pandas()

In [156]:
df.apply(upper_case, axis=1)

0      Alice
1        Bob
2    Charlie
3      Diana
4      Ethan
dtype: object

In [157]:
df.progress_apply(upper_case, axis=1)

100%|████████████████████████████████████████████████████████████████████████████████████| 5/5 [00:15<00:00,  3.00s/it]

0      Alice
1        Bob
2    Charlie
3      Diana
4      Ethan
dtype: object